resource_types:
- name: ali-oss-resource
  type: docker-image
  source:
      repository: gugege/concourse-aliyun-oss-resource
      tag: 0.1

resources:
- name: ali-oss
  type: ali-oss-resource
  source:
    endpoint: ((endpoint))
    accessKeyID: ((accessKeyID))
    accessKeySecret: ((accessKeySecret))
    git_private_key: ((git_private_key))

jobs:
- name: test put
  public: true
  plan:
  - task: upload task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gugege/node_12_4_cnpm_rsync
          tag: '1.0'
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          echo "testfile1" > ./upload_src/testfile1
          echo "testfile2" > ./upload_src/testfile2
          echo "testfile3" > ./upload_src/testfile3
          pwd
          ls -alhR .
      outputs:
      - name: upload_src
  - put: ali-oss
    params:
        cmd: "cp upload_src/testfile1 oss://h5-concourse/h5/test/testfile1 -u" #prefix_dir: oss://h5-concourse/h5 deploy_hash=test
        cmds:
        - "cp upload_src/testfile2 oss://h5-concourse/h5/test/testfile2 -u"
        - "cp upload_src/testfile3 oss://h5-concourse/h5/test/testfile3 -u"
        
- name: test get
  public: true
  plan:
  - get: ali-oss
    params:
      prefix_dir: oss://h5-concourse/h5
      git_url: git@gitee.com:buybuystore/h5-deploy.git
  - task: download task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gugege/node_12_4_cnpm_rsync
          tag: '1.0'
      inputs:
      - name: ali-oss
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          pwd
          ls -alhR .
      outputs:
      - name: upload_src